micronaut:
  application:
    name: clientCredentialIssue
  security:
    intercept-url-map: 
      -
        pattern: /*
        access:
          - isAnonymous()
    oauth2:
      clients:
        localauth:
          client-id: 'XXX'
          client-secret: 'XXX'
          token:
            url: "http://localhost:8080/token"
            auth-method: client_secret_basic
          client-credentials:
            service-id-regex: "/hello"
netty:
  default:
    allocator:
      max-order: 3
